import type { Metadata } from "next";
import "@/styles/globals.css";
import { Cormorant_Garamond, Sorts_Mill_Goudy } from "next/font/google";
import MobileMenu from "@/components/mobilemenu";
import fetchLinks from "@/utils/links";
import { unstable_cache } from "next/cache";

const cormorantGaramond = Cormorant_Garamond({
  weight: "400",
  style: ["normal"],
  display: "swap",
  subsets: ["latin"],
  variable: "--cormorant-garamond",
});

const goudy = Sorts_Mill_Goudy({
  weight: "400",
  style: ["normal"],
  display: "swap",
  subsets: ["latin"],
  variable: "--goudy",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = await unstable_cache(async () => { return await fetchLinks() }, ["links"], {
    revalidate: 3600
  })();

  return (
    <html lang="en">
      <body className={`${cormorantGaramond.variable} ${goudy.variable}`}>
        {/* <Header search={false}/> */}
        <MobileMenu links={links}/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
